---
title: "Memo1"
author: "Jessie Arroyo"
date: "2022-09-21"
output: html_document
---


## Reading the Data and Renaming some of the column names
```{r}
#setwd("~/Downloads/CrimeData") Setting a Directory
CrimeData <- read.csv("~/Downloads/CrimeData/crimedata.csv", na.strings="?", stringsAsFactors=TRUE)
colnames(CrimeData)[1] <- "Community Name" #Renaming
colnames(CrimeData)[3] <- "County Code" #Renaming
colnames(CrimeData)[4] <- "Community Code" #Renaming

# Viewing Dimension of the Dataset
dim(CrimeData)
Crimedata = na.omit(CrimeData)
```

## Using Min-Max standardization to normalize the data 

1. Download caret, to download caret, we click on "tools" then after click on "install packages", then search for "carnet" and click install 
```{r}
#minMax <- function(x) {
   # (x - min(x)) / (max(x) - min(x))
 # }
#normalizeCrimeData <- as.data.frame(lapply(CrimeData[6:147], minMax))
#apply Min-Max normalization to first four columns in iris dataset
#iris_norm <- as.data.frame(lapply(iris[1:4], min_max_norm))
#normalizeCrimeData

library(caret)
pp = preProcess(CrimeData, method = "range")
crimedata = predict(pp, CrimeData)
crimedata = na.omit(crimedata)
#Viewing Data
View(crimedata)

#Viewing the amount of rows and columns
ncol(crimedata)
nrow(crimedata)

```

## Splitting the Data into training and testing. 
```{r}
library(dplyr)

train = sample(nrow(crimedata), 0.6*nrow(crimedata)) #splitting the data
CrimeTr = crimedata[train,] #Creating Training Data set
CrimeTe = crimedata[-train,] # Creating test Data 

Xtrain = CrimeTr %>% select(population, householdsize, racepctblack:racePctHisp, agePct12t21:agePct65up, medIncome, pctWWage, pctWSocSec,NumUnderPov,PctLess9thGrade,PctNotHSGrad,PctBSorMore,PctUnemployed,PctEmploy,NumImmig,PctNotSpeakEnglWell,PctLargHouseOccup,PctLargHouseFam,HousVacant, PctVacantBoarded, PctVacMore6Mos,PctWOFullPlumb,PctForeignBorn,NumInShelters,NumStreet,NumKindsDrugsSeiz,PolicCars)

Xtest = CrimeTe %>% select(population, householdsize, racepctblack:racePctHisp, agePct12t21:agePct65up, medIncome, pctWWage, pctWSocSec,NumUnderPov,PctLess9thGrade,PctNotHSGrad,PctBSorMore,PctUnemployed,PctEmploy,NumImmig,PctNotSpeakEnglWell,PctLargHouseOccup,PctLargHouseFam,HousVacant, PctVacantBoarded, PctVacMore6Mos,PctWOFullPlumb,PctForeignBorn,NumInShelters,NumStreet,NumKindsDrugsSeiz,PolicCars)

Ytrain =  CrimeTr %>% select(robbbPerPop, burglPerPop,autoTheftPerPop,arsonsPerPop,larcPerPop,murdPerPop,rapesPerPop,assaultPerPop,ViolentCrimesPerPop,nonViolPerPop)

Ytest =  CrimeTe %>% select(robbbPerPop, burglPerPop,autoTheftPerPop,arsonsPerPop,larcPerPop,murdPerPop,rapesPerPop,assaultPerPop,ViolentCrimesPerPop,nonViolPerPop)
```


